### ISSUE TITLE
[question] About how assets are generated in gotty project

### ISSUE THREAD

**Issue by ngxlua** [navigaid/hello-wasm#1]
I am sorry to ask you this way,

can you tell me how the assets/assets.go file was generated, thanks

**Comment by ngxlua** [comment]
Maybe commit [6a97c5657edb707e04828e8b1f3a3be4fe220a9a](https://github.com/yudai/gotty/pull/256/commits/6a97c5657edb707e04828e8b1f3a3be4fe220a9a) is correct,

Because I execute the top command after gotty zsh, I get an error.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/31426367/60511491-b397a280-9d04-11e9-877f-d2a0bf9c811d.png">


Also, can we try to upgrade xterm.js to the latest version? Looking forward to your reply.

**Comment by ngxlua** [comment]
I am sorry for the behavior like me, but I hope to learn from you.

**Comment by navigaid** [comment]
@ngxlua it's generated from this:
https://github.com/navigaid/gotty/blob/study/Makefile#L15

make sure you install the `assets` tool first:
https://github.com/navigaid/gotty/blob/study/Makefile#L67

**Comment by navigaid** [comment]
Also, npm dependencies are updated to the latest version. 
https://github.com/navigaid/gotty/commit/d4de8d834f67fb624a8b1cf85a79e03b074dbbd1

If you have further questions, open a new issue here https://github.com/navigaid/gotty/issues

**Comment by itchenyi** [comment]
@navigaid 
Thanks for your reply, as well as the optimization and adjustment of the gotty code
